### ISSUE TITLE
【Suggestion】

### ISSUE THREAD

**Issue by xlj633** [CatalinTermure/Cytoid-Chart-Editor#1]
First, I think I need to add a vertical grid adjustment (maybe I didn't find it?)
Secondly, in the editing state, I think it is not necessary to preview the previous note, which may cause confusion when you edit.
Finally, I hope to increase the control over the size of the notes to suit the habits of more people and the special effects of percussion instruments. Now, the special effect of not being hit looks strange.
(Maybe the music is a bit off? The exact note I previewed on Pctyx may be a bit off here)

**Comment by CatalinTermure** [comment]
Vertical grid adjustment will be added in the next update.
I stand by the fact that the notes on the previous page should be shown to avoid overlaps, which are very annoying to play.
Note size and different hitsounds(the special effects) will be added in a later date, I will keep this issue open until they do, so rest assured.
The timing might be a bit off from Pctyx due to hardware latency on android devices. The editor works around it with the help of the music offset set by the first note scanline note(more on this in the wiki). You should also keep this in mind when uploading to cytoid, when you should manually adjust the music offset to suit the chart. This is probably how it will be kept since even cytoid struggles with this issue, although I will strive to make the latency consistent with cytoid's.

**Comment by xlj633** [comment]
Thank you, but I still have a question, how to write a multi-screen drag, it seems that drag can only be written on one page now

**Comment by CatalinTermure** [comment]
Ah, this is actually a feature that is enabled by the fact that you can see notes on the previous page. If you go to a page, you can see drag heads/children on the previous page, so you can select the drag note on the previous page and add a child to it that is on the current page.
Also if you want to make it span more than 2 pages, you can make something like drag head on page X, drag child on page X + 1, drag child on page X + 2 and delete the child on page X + 1, the drag head on page X will still remain connected to the child on page X + 2.

**Comment by CatalinTermure** [comment]
With the addition of custom hitsounds in the most recent commit and the other suggestions having been added already, I feel this issue can be closed.
