### ISSUE TITLE
Show note IDs

### ISSUE THREAD

**Issue by iJustGhost** [CatalinTermure/Cytoid-Chart-Editor#35]
I would love to have this feature added, it's for storyboard making purposes... The official Cytoid player doesn't perform well on my PC so this is my only hope.

**Comment by CatalinTermure** [comment]
Will do.
If you don't mind, can you specify what doesn't work so well?
Is chart playing laggy? or maybe operations like adding notes and removing take a while?
Also, apologies for taking so long to answer.

**Comment by camelCase-dumb** [comment]
Haha I thought this repo is inactive, this android app is performing so well it's almost perfect so I don't have problems with it.

The Cytoid Player in PC is lagging so much I don't know if it's the Player's fault or my PC, sometimes the Player suddenly Freezes so i have to restart my PC.

**Comment by CatalinTermure** [comment]
Currently the repo is in a less active state because the codebase is starting to show signs of technical debt, so I am rewriting most of it, while learning how to better write code(and also busy with other projects unrelated to this).
But since it's in the middle of a rewrite, it's not operational and my philosophy is to not upload code that does not work.
This rewrite includes a lot of performance optimizations and multi-threading(which is important for PC performance) so that may solve your issues.
Storyboarding will follow closely after, though with limited functionality which will be built upon progressively. Not sure if I will do previewing separately before starting editing, though. Will have to consider that.

**Comment by CatalinTermure** [comment]
After a long break, finally added this. :D

**Comment by iJustGhost** [comment]
A legendary comeback :O
